pipelines:
  branches:
    master:
      - step:
          name: Mirror Repository Changes to GitHub
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - echo "Running Script"
            - echo "New tag $BITBUCKET_TAG"
            - if [ "$BITBUCKET_TAG" ]; then
                - echo "Triggered on tag creation"
                - git clone --bare --branch master git@bitbucket.org:appzonegroup/sourcecode-backup-test.git
                - cd sourcecode-backup-test.git
                - git push --mirror git@github.com:tobeoct/heritage-middleware.git
                - echo "Mirroring Completed"
            - fi;
  tags:
    '*':
      - step:
          name: Mirror to GitHub
          image: alpine/git
          script:
            - git fetch --all --tags
            - TAG_COMMIT=$(git rev-list -n 1 $BITBUCKET_TAG)
            - BRANCH_NAME=$(git branch -a --contains $TAG_COMMIT)
            - echo "Branch name $BRANCH_NAME"
            - if [[ "$BRANCH_NAME" =~ "master" ]]; then
              - echo "Triggered on tag creation"
              - git clone --bare --branch master git@bitbucket.org:appzonegroup/sourcecode-backup-test.git
              - cd sourcecode-backup-test.git
              - git push --mirror git@github.com:tobeoct/heritage-middleware.git
              - echo "Mirroring Completed"
            - fi;