pipelines:
  branches:
    master:
      - step:
          name: Mirror Repository Changes to GitHub
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - if [ "$BITBUCKET_TAG" ]; then
                - echo "Triggered on tag creation"
                - git clone --bare git@bitbucket.org:appzonegroup/sourcecode-backup-test.git
                - cd sourcecode-backup-test.git
                - git push --mirror git@github.com:tobeoct/heritage-middleware.git
                - echo "Mirroring Completed"
            - fi;