pipelines:
  branches:
    master:
      - step:
          name: Mirror Repository Changes to GitHub
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - echo "Running Script"
            - echo "$BITBUCKET_TAG"
            - if [ "$BITBUCKET_TAG" ]; then
                - echo "Triggered on tag creation"
                - git clone --bare --branch master git@bitbucket.org:appzonegroup/sourcecode-backup-test.git
                - cd sourcecode-backup-test.git
                - git push --mirror git@github.com:tobeoct/heritage-middleware.git
                - echo "Mirroring Completed"
            - fi;
  tags:
    '*':
      - step:
          name: Mirror to GitHub
          image: alpine/git
          script:
            - echo "Running Script"
            - if [[ "$BITBUCKET_BRANCH" =~ ^master$ ]]; then
              - echo "Triggered on tag creation"
              - git clone --bare --branch master git@bitbucket.org:appzonegroup/sourcecode-backup-test.git
              - cd sourcecode-backup-test.git
              - git push --mirror git@github.com:tobeoct/heritage-middleware.git
              - echo "Mirroring Completed"
            - fi;