pipelines:
  branches:
    master:
      - step:
          name: Mirror Repository Changes to GitHub
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - echo "Running Script"
            - echo "New tag $BITBUCKET_TAG"
            - if [ "$BITBUCKET_TAG" ]; then
                - echo "Triggered on tag creation"
                - git clone --bare --tags --branch master git@bitbucket.org:appzonegroup/sourcecode-backup-test.git
                - cd sourcecode-backup-test.git
                - git push --mirror git@github.com:tobeoct/sourcecode-backup-poc-bitbucket.git
                - echo "Mirroring Completed"
            - fi;
  tags:
    '*':
      - step:
          name: Mirror to GitHub
          image: alpine/git
          script:
            - echo "Triggered on tag creation"
            - git clone --bare --tags --branch master git@bitbucket.org:appzonegroup/sourcecode-backup-test.git
            - cd sourcecode-backup-test.git
            - git push --mirror git@github.com:tobeoct/sourcecode-backup-poc-teamcity.git
            - echo "Mirroring Completed"